version: "3.7"
services:

    web:
      image: wiotrek/electronic-diary-web:latest
      ports:
      - "4200:80"
      networks:
        vpcbr:
          ipv4_address: 10.10.0.3

    server:
      image: wiotrek/image
      depends_on:
        - mysql
      volumes:
        - ./:/app/src
      networks:
          vpcbr:
              ipv4_address: 10.10.0.2

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
           - MYSQL_ROOT_PASSWORD=password
           - MYSQL_ROOT_HOST=%
        volumes:
           - ./data/mysql:/var/lib/mysql
           - ./db-init:/docker-entrypoint-initdb.d
        networks:
             vpcbr:
                 ipv4_address: 10.10.0.4

networks:
    vpcbr:
        driver: bridge
        ipam:
           config:
               - subnet: 10.10.0.0/16